markup:
  # Markup
  # We assume we're using Goldmark
  # https://gohugo.io/getting-started/configuration-markup#readout
  # ################################
  highlight:
    style: monokai
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true
module:
  mounts:
  - source: layouts
    target: layouts
  - source: core
    target: layouts/partials/huge

  imports:
  - path: github.com/theNewDynamic/hugo-module-tnd-styles
  - path: github.com/theNewDynamic/hugo-module-tnd-scripts
  - path: github.com/theNewDynamic/hugo-module-tnd-seo